//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GtKram.Ui.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GtKram.Ui.I18n.LocalizedMessages", typeof(LocalizedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikel wurde nicht gefunden..
        /// </summary>
        internal static string ArticleNotFound {
            get {
                return ResourceManager.GetString("ArticleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Wert &apos;{0}&apos; ist für das Feld &apos;{1}&apos; ungültig..
        /// </summary>
        internal static string AttemptedValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("AttemptedValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Kinderbasar ist bereits abgelaufen..
        /// </summary>
        internal static string BazaarExpired {
            get {
                return ResourceManager.GetString("BazaarExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Kinderbasar ist nicht freigegeben..
        /// </summary>
        internal static string BazaarNoAssigned {
            get {
                return ResourceManager.GetString("BazaarNoAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinderbasar wurde nicht gefunden..
        /// </summary>
        internal static string BazaarNotFound {
            get {
                return ResourceManager.GetString("BazaarNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Registrierungen für den Kinderbasar sind nicht abgeschlossen..
        /// </summary>
        internal static string BazaarRegsiterUncomplete {
            get {
                return ResourceManager.GetString("BazaarRegsiterUncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kassen-Vorgang wurde nicht gefunden..
        /// </summary>
        internal static string BillingNotFound {
            get {
                return ResourceManager.GetString("BillingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Kassieren ist nicht erlaubt..
        /// </summary>
        internal static string CreateBillingsForbidden {
            get {
                return ResourceManager.GetString("CreateBillingsForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikel können nicht bearbeitet werden. Die Bearbeitungszeit ist abgelaufen..
        /// </summary>
        internal static string EditArticleExpired {
            get {
                return ResourceManager.GetString("EditArticleExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Feld &apos;{0}&apos; muss eine Zahl sein..
        /// </summary>
        internal static string FieldMustBeANumberAccessor {
            get {
                return ResourceManager.GetString("FieldMustBeANumberAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Link zum Bestätigen der Registrierung ist ungültig oder abgelaufen. Eine neue Anfrage ist notwendig..
        /// </summary>
        internal static string InvalidAccountConfirmationLink {
            get {
                return ResourceManager.GetString("InvalidAccountConfirmationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die E-Mail-Adresse ist ungültig..
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Link zum Bestätigen der neuen E-Mail-Adresse ist ungültig oder abgelaufen. Eine neue Anfrage ist notwendig..
        /// </summary>
        internal static string InvalidNewEmailConfirmationLink {
            get {
                return ResourceManager.GetString("InvalidNewEmailConfirmationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Link zum Zurücksetzen des Passworts ist ungültig oder abgelaufen. Eine neue Anfrage ist notwendig..
        /// </summary>
        internal static string InvalidPasswordResetLink {
            get {
                return ResourceManager.GetString("InvalidPasswordResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Anfrage ist ungültig..
        /// </summary>
        internal static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Wert &apos;{0}&apos; ist ungültig..
        /// </summary>
        internal static string NonPropertyAttemptedValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("NonPropertyAttemptedValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Speichern..
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Verkäufer wurde nicht gefunden..
        /// </summary>
        internal static string SellerNotFound {
            get {
                return ResourceManager.GetString("SellerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Feld &apos;{0}&apos; muss eine Zahl sein..
        /// </summary>
        internal static string ValueMustBeANumberAccessor {
            get {
                return ResourceManager.GetString("ValueMustBeANumberAccessor", resourceCulture);
            }
        }
    }
}
